project(
  'LunaLauncher',
  ['c', 'cpp', 'java'],
  version: '11.0.3',
  meson_version: '>=1.4.0',
  default_options: [
    'buildtype=release',
    'b_ndebug=if-release',
    'b_vscrt=md',
    'c_std=c11',
    'cpp_std=c++20',
    'warning_level=0',
  ],
)

host_system = host_machine.system()
is_windows = host_system == 'windows'
is_linux = host_system == 'linux'

if not is_windows and not is_linux
  error('This Meson build currently supports Windows and Linux targets.')
endif

if meson.project_source_root() == meson.project_build_root()
  error('In-source Meson builds are not supported.')
endif

qt = import('qt6')
if is_windows
  windows = import('windows')
endif

git_prog = find_program('git', required: false)
python_prog = find_program('python', required: true)

cc = meson.get_compiler('c')
cpp = meson.get_compiler('cpp')

if cpp.get_argument_syntax() == 'msvc'
  add_project_arguments(
    [
      '-DUNICODE',
      '-D_UNICODE',
      '/permissive-',
      '/Zc:__cplusplus',
      '/Zc:preprocessor',
      '/utf-8',
      '/W4',
      '/wd4100',
    ],
    language: 'cpp',
  )
  add_project_link_arguments(['/STACK:8388608'], language: ['c', 'cpp'])
else
  add_project_arguments(
    [
      '-fstack-protector-strong',
      '-DQT_NO_DEBUG',
    ],
    language: ['c', 'cpp'],
  )
  if cpp.has_argument('-Wno-sfinae-incomplete')
    add_project_arguments('-Wno-sfinae-incomplete', language: 'cpp')
  endif
endif

add_project_arguments(
  [
    '-DQT_WARN_DEPRECATED_UP_TO=0x060400',
    '-DQT_DISABLE_DEPRECATED_UP_TO=0x060400',
  ],
  language: 'cpp',
)

qt_dependency_method = is_windows ? 'cmake' : 'pkg-config'
qt_core_dep = dependency('Qt6Core', method: qt_dependency_method, required: true)
qt_widgets_dep = dependency('Qt6Widgets', method: qt_dependency_method, required: true)
qt_network_dep = dependency('Qt6Network', method: qt_dependency_method, required: true)
qt_networkauth_dep = dependency('Qt6NetworkAuth', method: qt_dependency_method, required: true)
qt_concurrent_dep = dependency('Qt6Concurrent', method: qt_dependency_method, required: true)
qt_websockets_dep = dependency('Qt6WebSockets', method: qt_dependency_method, required: true)
qt_xml_dep = dependency('Qt6Xml', method: qt_dependency_method, required: true)
qt_gui_dep = dependency('Qt6Gui', method: qt_dependency_method, required: true)
qt_test_dep = dependency('Qt6Test', method: qt_dependency_method, required: true)
qt_opengl_dep = dependency('Qt6OpenGL', method: qt_dependency_method, required: true)
qt_multimedia_dep = dependency('Qt6Multimedia', method: qt_dependency_method, required: true)
qt_dbus_dep = dependency('Qt6DBus', method: qt_dependency_method, required: false)
if is_windows
  qt_entrypoint_dep = cpp.find_library(
    'Qt6EntryPoint',
    dirs: [meson.project_source_root() / 'third_party/qt/6.10.1/msvc2022_64/lib'],
    required: true,
  )
else
  qt_entrypoint_dep = dependency('', required: false)
endif

zlib_dep = dependency('zlib', fallback: ['zlib', 'zlib_dep'], required: true)
libarchive_dep = dependency('libarchive', fallback: ['libarchive', 'libarchive_dep'], required: true)
libqrencode_dep = dependency('libqrencode', fallback: ['qrencode', 'qrencode_dep'], required: true)
tomlplusplus_dep = dependency('tomlplusplus', fallback: ['tomlplusplus', 'tomlplusplus_dep'], required: true)

threads_dep = dependency('threads', required: false)
dl_dep = dependency('dl', required: false)
math_dep = cc.find_library('m', required: false)
gamemode_dep = dependency('gamemode', required: is_linux ? get_option('gamemode') : false)

launcher_name = 'LunaLauncher'
launcher_common_name = 'LunaLauncher'
launcher_display_name = 'Luna Launcher'
launcher_app_binary_name = 'lunalauncher'
launcher_app_id = 'org.lunalauncher.LunaLauncher'
launcher_svg_file_name = 'org.lunalauncher.LunaLauncher.svg'
launcher_env_name = 'LUNALAUNCHER'
launcher_domain = 'lunalauncher.org'
launcher_config_file = 'lunalauncher.cfg'
launcher_git_url = 'https://github.com/AndreaFrederica/LunaLauncher'
launcher_copyright = '© 2025 Luna Launcher Contributors\\n© 2022-2025 Prism Launcher Contributors\\n© 2021-2022 PolyMC Contributors\\n© 2012-2021 MultiMC Contributors'
launcher_version_parts = meson.project_version().split('.')
launcher_version_major = launcher_version_parts[0].to_int()
launcher_version_minor = launcher_version_parts[1].to_int()
launcher_version_patch = launcher_version_parts[2].to_int()
launcher_version_prerelease = ''
launcher_version_name = '@0@.@1@.@2@'.format(launcher_version_major, launcher_version_minor, launcher_version_patch)
launcher_version_name4 = '@0@.@1@.@2@.0'.format(launcher_version_major, launcher_version_minor, launcher_version_patch)
launcher_version_name4_comma = '@0@,@1@,@2@,0'.format(launcher_version_major, launcher_version_minor, launcher_version_patch)
launcher_build_platform = '@0@-@1@'.format(host_machine.system(), host_machine.cpu_family())
launcher_updater_github_repo = 'https://github.com/AndreaFrederica/LunaLauncher'
launcher_build_artifact = ''
launcher_news_rss_url = 'https://prismlauncher.org/feed/feed.xml'
launcher_news_open_url = 'https://prismlauncher.org/news'
launcher_wiki_url = 'https://prismlauncher.org/wiki/'
launcher_help_url = 'https://prismlauncher.org/wiki/help-pages/%1'
launcher_login_callback_url = 'https://lunalauncher.sirrus.cc/oauth-callback.html'
launcher_legacy_fmllibs_base_url = 'https://files.prismlauncher.org/fmllibs/'
launcher_meta_url = 'https://meta.prismlauncher.org/v1/'
launcher_imgur_client_id = '5b97b0713fba4a3'
launcher_bug_tracker_url = 'https://github.com/AndreaFrederica/LunaLauncher/issues'
launcher_translations_url = 'https://hosted.weblate.org/projects/prismlauncher/launcher/'
launcher_translation_files_url = 'https://i18n.prismlauncher.org/'
launcher_matrix_url = 'https://prismlauncher.org/matrix'
launcher_discord_url = 'https://prismlauncher.org/discord'
launcher_subreddit_url = 'https://prismlauncher.org/reddit'
launcher_user_agent = '@0@/@1@'.format(launcher_common_name, launcher_version_name)
launcher_glfw_library_name = 'glfw.dll'
launcher_openal_library_name = 'OpenAL.dll'
launcher_msa_client_id = 'a60a8e54-8c3c-4b25-9fe4-8ec4e616c410'
launcher_curseforge_api_key = '$2a$10$wuAJuNZuted3NORVmpgUC.m8sI.pv1tOPKZyBgLFGjxFp/br0lZCC'
launcher_enable_java_downloader = get_option('enable_java_downloader')
launcher_disable_ownership_check = get_option('disable_ownership_check')
launcher_bundle_aria2c = get_option('bundle_aria2c')
launcher_aria2c_path = get_option('aria2c_path')

git_commit = ''
git_tag = 'GIT-NOTFOUND'
git_refspec = 'refs/heads/stable'
if git_prog.found()
  git_commit_result = run_command(git_prog, 'rev-parse', 'HEAD', check: false)
  if git_commit_result.returncode() == 0
    git_commit = git_commit_result.stdout().strip()
  endif

  git_tag_result = run_command(git_prog, 'describe', '--tags', '--exact-match', check: false)
  if git_tag_result.returncode() == 0
    git_tag = git_tag_result.stdout().strip()
  endif

  git_refspec_result = run_command(git_prog, 'symbolic-ref', 'HEAD', check: false)
  if git_refspec_result.returncode() == 0
    git_refspec = git_refspec_result.stdout().strip()
  elif git_commit != ''
    git_refspec = git_commit.substring(0, 8)
  endif
endif

build_date = run_command(
  python_prog,
  '-c',
  'import datetime; print(datetime.date.today().isoformat())',
  check: true,
).stdout().strip()

compiler_name = cpp.get_id()
compiler_version = cpp.version()
compiler_target_system = host_machine.system()
compiler_target_system_version = host_machine.kernel()
compiler_target_processor = host_machine.cpu_family()

if is_linux
  binary_dest_dir = 'bin'
  runtime_data_dest_dir = join_paths(get_option('datadir'), launcher_name)
  jars_dest_dir = runtime_data_dest_dir
  resources_dest_dir = runtime_data_dest_dir
  exresource_dest_dir = join_paths(runtime_data_dest_dir, 'resources')
else
  binary_dest_dir = '.'
  jars_dest_dir = 'jars'
  resources_dest_dir = '.'
  exresource_dest_dir = 'resource'
endif
library_dest_dir = '.'
plugin_dest_dir = '.'
framework_dest_dir = '.'

subdir('program_info')
subdir('buildconfig')
subdir('libraries/cmark')
subdir('libraries')
subdir('launcher')

if get_option('build_testing')
  subdir('tests')
endif

summary(
  {
    'Version': meson.project_version(),
    'Target platform': launcher_build_platform,
    'Install prefix': get_option('prefix'),
    'Runtime data': resources_dest_dir,
    'Tests': get_option('build_testing'),
    'Java downloader': launcher_enable_java_downloader,
    'Ownership check disabled': launcher_disable_ownership_check,
    'GameMode': gamemode_dep.found(),
    'Bundled aria2c': launcher_bundle_aria2c,
  },
  section: 'Luna Launcher',
  bool_yn: true,
)
